
services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    image: gcp-pmle-quiz-streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data:rw
    environment:
      - STREAMLIT_SERVER_ENABLECORS=false
      - STREAMLIT_SERVER_RUN_ON_SAVE=false
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_LOG_LEVEL=info
      - UV_NO_DEV=1

    restart: unless-stopped